infra:
    log_dir: ./ # where all the experiments are
    exp_name: opensrh # use the same name as the training experiment
    comment: dev # use the same comment as the training experiment
    seed: 1000
data:
    db_root: /path/to/opensrh/
model:
    backbone: resnet50 # ["resnet50", "vit"]
    #backbone_params: # for vit backbone only
    #    model_name: vit_small_patch16_224
    #    pretrained: false
    mlp_hidden: []
    num_embedding_out: 128
eval:
    ckpt_path: relative/path/to/checkpoint.ckpt # eg. hash_datetime_expname_comment/models/ckpt-epochXX-accXXX.ckpt
