infra:
    log_dir: ./ # where all the experiments are
    exp_name: opensrh # create a subdirectory for each set of experiments
    comment: dev # can use this to customize for each experiment
    seed: 1000
data:
    db_root: /path/to/opensrh/ 
    train_augmentation:
    - which: random_horiz_flip
      params: {}
    - which: random_vert_flip
      params: {}
    #- which: resize # for vit backbone only
    #  params:
    #    size: 224
    valid_augmentation: [] 
    #valid_augmentation: 
    #- which: resize # for vit backbone only
    #  params:
    #    size: 224
    rand_aug_prob: 0.5
    balance_patch_per_class: true
model:
    backbone: resnet50 # [resnet50, vit]
    #backbone_params: # for vit backbone only
    #    model_name: vit_small_patch16_224
    #    pretrained: false
    mlp_hidden: []
training:
    batch_size: 56 
    num_epochs: 20
    optimizer: adamw # supports sgd, adam, adamw
    learn_rate: 1.0e-3
    scheduler:
        which: step_lr
        params:
            step_size: 1
            step_unit: epoch # epoch or iter
            gamma: 0.5
    #    which: cos_warmup # for cosine lr with warmup
    #    params:
    #        num_warmup_steps: 0.1
    #        num_cycles: 0.3
    imagenet_backbone_checkpoint: null
